[package]
name = "angry-bonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turbo = { version = "1.2.1", package = "turbo-genesis-sdk", features = [
"solana",
]}

[lib]
crate-type = ["cdylib"]
